baseURL = "https://blog.7seven.xyz"  # <head> 里面的 baseurl 信息，填你的博客地址
title = "小琪気的博客"     # 浏览器的标题
theme = "hugo-coder"     # 主题 (需要自己下载)
languagecode = "zh-cn"   # 语言
defaultcontentlanguage = "zh-cn"

paginate = 9999          # 每页的文章数
enableEmoji = true       # 支持 Emoji
enableRobotsTXT = true   # 支持 robots.txt
canonifyURLs = true      #  启用将相对URL转换为绝对URL
googleAnalytics = ""     # Google 统计 id

pygmentsStyle = "b2"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
#disqusShortname = "yourdiscussshortname"
pluralizelisttitles = false

FootnoteReturnLinkContents = "↑"

# 是否在文档中直接使用 HTML 标签
[markup.goldmark.renderer]
    unsafe= true

# 用于 Hugo 输出文档的设置
[outputs]
  page     = ["HTML", "AMP"]
  home     = ["HTML", "RSS"]
  section  = ["HTML"]
  taxonomyTerm = ["HTML"]
  taxonomy = ["HTML"]

# 自定义分类
[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[params]
    author = "7.seven"
    info1 = "Just for Fun"
    info2 = "Learner"
    info3 = ""
    description = ""
    keywords = ""

    #github = ""
    #telegram = ""
    #zhihu = ""
    #wechat = ""

    favicon_32 = "images/f/favicon-32x32.png"
    favicon_16 = "images/f/favicon-16x16.png"

    hidecredits = true
    hidecopyright = false

    math = true
    #custom_css = ["/css/main.css"]
    #custom_js = ["/js/lazysizes.min.js", "/js/flying-pages.min.js", "/js/custom.js"]

    dateFormat = "2020-11-22"
    series = true
    rtl = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorscheme = "auto"

    # Series see also post count
    maxSeeAlsoItems = 3

# Comments on github issue
[params.utteranc]
    repo = "JakATom/7.seven"
    issue-term = "pathname"
    theme = "github-light"

## 开启版权声明，协议名字和链接都可以换
[params.cc]
    name = "知识共享署名-非商业性使用-禁止演绎 4.0 国际许可协议"
    link = "https://creativecommons.org/licenses/by-nc-nd/4.0/"

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/JakATom/7.seven"

[[params.social]]
    name = "RSS"
    icon = "fas fa-rss"
    weight = 2
    url = "index.xml"

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 2

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3

  [[menu.main]]
    name = "About"
    url = "/about.md"
    weight = 4