baseURL = "https://blog.7seven.xyz"  # <head> 里面的 baseurl 信息，填你的博客地址
title = "小琪気的博客"     # 浏览器的标题
theme = "hugo-coder"     # 主题 (需要自己下载)
languagecode = "zh-cn"   # 语言
hasCJKLanguage = true # 开启可以让「字数统计」统计汉字

paginate = 9999          # 每页的文章数
enableEmoji = true       # 支持 Emoji
enableRobotsTXT = true   # 支持 robots.txt

canonifyURLs = true      #  启用将相对URL转换为绝对URL
googleAnalytics = ""     # Google 统计 id

pygmentsStyle = "b2"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
pluralizelisttitles = false

FootnoteReturnLinkContents = "↑"

# 生成的文章的路径
[Permalinks]
  posts = "/posts/:slug.html"

# 自定义分类
[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

# 主页内容
[params]
    author = "7.seven"
    avatarurl = "images/maomi.jpg"
    subtitle = "HALO HALO" 

    description = "小琪気的博客"
    keywords = "blog, 随笔"
    enableUtteranc = true # utteranc 评论系统

    license= '本文采用<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/" target="_blank">知识共享署名-非商业性使用 4.0 国际许可协议</a>进行许可'

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorscheme = "auto"

# Comments on github issue
[params.utteranc]
    repo = "JakATom/7.seven"
    issue-term = "pathname"
    theme = "github-light"

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/JakATom/7.seven"

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 2

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4

[markup.goldmark.renderer]
    unsafe = true